# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('TERGMdir_rowsum_Mat', PACKAGE = 'TERGMdir', M)
}

colsum_Mat <- function(M) {
    .Call('TERGMdir_colsum_Mat', PACKAGE = 'TERGMdir', M)
}

epan <- function(input) {
    .Call('TERGMdir_epan', PACKAGE = 'TERGMdir', input)
}

gamma_update_TERGM_dir <- function(gamma, pi, theta, network, N, K, T_data) {
    .Call('TERGMdir_gamma_update_TERGM_dir', PACKAGE = 'TERGMdir', gamma, pi, theta, network, N, K, T_data)
}

grad_TERGM_dir_oe <- function(theta, gamma, network, N, K, T_data) {
    .Call('TERGMdir_grad_TERGM_dir_oe', PACKAGE = 'TERGMdir', theta, gamma, network, N, K, T_data)
}

grad_TERGM_dir_re <- function(theta, gamma, network, N, K, T_data) {
    .Call('TERGMdir_grad_TERGM_dir_re', PACKAGE = 'TERGMdir', theta, gamma, network, N, K, T_data)
}

hess_TERGM_dir_oe <- function(theta, gamma, N, K, T_data) {
    .Call('TERGMdir_hess_TERGM_dir_oe', PACKAGE = 'TERGMdir', theta, gamma, N, K, T_data)
}

hess_TERGM_dir_re <- function(theta, gamma, N, K, T_data) {
    .Call('TERGMdir_hess_TERGM_dir_re', PACKAGE = 'TERGMdir', theta, gamma, N, K, T_data)
}

hess_TERGM_dir_oe_re <- function(theta, gamma, N, K, T_data) {
    .Call('TERGMdir_hess_TERGM_dir_oe_re', PACKAGE = 'TERGMdir', theta, gamma, N, K, T_data)
}

ELBO_conv_TERGM_dir <- function(gamma, pi, theta, network, N, K, T_data) {
    .Call('TERGMdir_ELBO_conv_TERGM_dir', PACKAGE = 'TERGMdir', gamma, pi, theta, network, N, K, T_data)
}

grad_TERGM_dir_K1_oe <- function(theta, network, N, T_data) {
    .Call('TERGMdir_grad_TERGM_dir_K1_oe', PACKAGE = 'TERGMdir', theta, network, N, T_data)
}

grad_TERGM_dir_K1_re <- function(theta, network, N, T_data) {
    .Call('TERGMdir_grad_TERGM_dir_K1_re', PACKAGE = 'TERGMdir', theta, network, N, T_data)
}

hess_TERGM_dir_K1_oe <- function(theta, N, T_data) {
    .Call('TERGMdir_hess_TERGM_dir_K1_oe', PACKAGE = 'TERGMdir', theta, N, T_data)
}

hess_TERGM_dir_K1_re <- function(theta, N, T_data) {
    .Call('TERGMdir_hess_TERGM_dir_K1_re', PACKAGE = 'TERGMdir', theta, N, T_data)
}

hess_TERGM_dir_K1_oe_re <- function(theta, N, T_data) {
    .Call('TERGMdir_hess_TERGM_dir_K1_oe_re', PACKAGE = 'TERGMdir', theta, N, T_data)
}

ELBO_conv_TERGM_dir_K1 <- function(theta, network, N, T_data) {
    .Call('TERGMdir_ELBO_conv_TERGM_dir_K1', PACKAGE = 'TERGMdir', theta, network, N, T_data)
}

