# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('HMMEMdir_rowsum_Mat', PACKAGE = 'HMMEMdir', M)
}

colsum_Mat <- function(M) {
    .Call('HMMEMdir_colsum_Mat', PACKAGE = 'HMMEMdir', M)
}

epan <- function(input) {
    .Call('HMMEMdir_epan', PACKAGE = 'HMMEMdir', input)
}

gamma_init_update_HMM_dir <- function(gamma_init, log_alpha, theta, network_init, N, K) {
    .Call('HMMEMdir_gamma_init_update_HMM_dir', PACKAGE = 'HMMEMdir', gamma_init, log_alpha, theta, network_init, N, K)
}

gamma_update_HMM_dir <- function(gamma_init, Tau, N, K, T_data) {
    .Call('HMMEMdir_gamma_update_HMM_dir', PACKAGE = 'HMMEMdir', gamma_init, Tau, N, K, T_data)
}

Tau_update_HMM_dir <- function(gamma, log_pi, theta, network, N, K, T_data) {
    .Call('HMMEMdir_Tau_update_HMM_dir', PACKAGE = 'HMMEMdir', gamma, log_pi, theta, network, N, K, T_data)
}

grad_HMM_dir_oe <- function(theta, gamma, network, N, K, T_data) {
    .Call('HMMEMdir_grad_HMM_dir_oe', PACKAGE = 'HMMEMdir', theta, gamma, network, N, K, T_data)
}

grad_HMM_dir_re <- function(theta, gamma, network, N, K, T_data) {
    .Call('HMMEMdir_grad_HMM_dir_re', PACKAGE = 'HMMEMdir', theta, gamma, network, N, K, T_data)
}

hess_HMM_dir_oe <- function(theta, gamma, N, K, T_data) {
    .Call('HMMEMdir_hess_HMM_dir_oe', PACKAGE = 'HMMEMdir', theta, gamma, N, K, T_data)
}

hess_HMM_dir_re <- function(theta, gamma, N, K, T_data) {
    .Call('HMMEMdir_hess_HMM_dir_re', PACKAGE = 'HMMEMdir', theta, gamma, N, K, T_data)
}

hess_HMM_dir_oe_re <- function(theta, gamma, N, K, T_data) {
    .Call('HMMEMdir_hess_HMM_dir_oe_re', PACKAGE = 'HMMEMdir', theta, gamma, N, K, T_data)
}

ELBO_conv_HMM_dir <- function(gamma, alpha, pi, Tau, theta, network, N, K, T_data) {
    .Call('HMMEMdir_ELBO_conv_HMM_dir', PACKAGE = 'HMMEMdir', gamma, alpha, pi, Tau, theta, network, N, K, T_data)
}

grad_HMM_dir_oe_K1 <- function(theta, network, N, T_data) {
    .Call('HMMEMdir_grad_HMM_dir_oe_K1', PACKAGE = 'HMMEMdir', theta, network, N, T_data)
}

grad_HMM_dir_re_K1 <- function(theta, network, N, T_data) {
    .Call('HMMEMdir_grad_HMM_dir_re_K1', PACKAGE = 'HMMEMdir', theta, network, N, T_data)
}

hess_HMM_dir_oe_K1 <- function(theta, N, T_data) {
    .Call('HMMEMdir_hess_HMM_dir_oe_K1', PACKAGE = 'HMMEMdir', theta, N, T_data)
}

hess_HMM_dir_re_K1 <- function(theta, N, T_data) {
    .Call('HMMEMdir_hess_HMM_dir_re_K1', PACKAGE = 'HMMEMdir', theta, N, T_data)
}

hess_HMM_dir_oe_re_K1 <- function(theta, N, T_data) {
    .Call('HMMEMdir_hess_HMM_dir_oe_re_K1', PACKAGE = 'HMMEMdir', theta, N, T_data)
}

ELBO_conv_HMM_dir_K1 <- function(theta, network, N, T_data) {
    .Call('HMMEMdir_ELBO_conv_HMM_dir_K1', PACKAGE = 'HMMEMdir', theta, network, N, T_data)
}

