// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;
using namespace std;

// rowsum_Mat
vec rowsum_Mat(mat M);
RcppExport SEXP TERGMdirTrans_rowsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// colsum_Mat
vec colsum_Mat(mat M);
RcppExport SEXP TERGMdirTrans_colsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(colsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// epan
float epan(float input);
RcppExport SEXP TERGMdirTrans_epan(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(epan(input));
    return rcpp_result_gen;
END_RCPP
}
// Trans_stat_cal
cube Trans_stat_cal(cube network, int N, int T_data);
RcppExport SEXP TERGMdirTrans_Trans_stat_cal(SEXP networkSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Trans_stat_cal(network, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update_TERGM_dir_Trans
cube gamma_update_TERGM_dir_Trans(mat gamma, vec pi, vec theta, cube network, cube Trans_stat, int N, int K, int T_data);
RcppExport SEXP TERGMdirTrans_gamma_update_TERGM_dir_Trans(SEXP gammaSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update_TERGM_dir_Trans(gamma, pi, theta, network, Trans_stat, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// grad_TERGM_dir_Trans
mat grad_TERGM_dir_Trans(vec theta, mat gamma, cube network, cube Trans_stat, int N, int K, int T_data);
RcppExport SEXP TERGMdirTrans_grad_TERGM_dir_Trans(SEXP thetaSEXP, SEXP gammaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_TERGM_dir_Trans(theta, gamma, network, Trans_stat, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// hess_TERGM_dir_Trans
mat hess_TERGM_dir_Trans(vec theta, mat gamma, int N, int K, int T_data);
RcppExport SEXP TERGMdirTrans_hess_TERGM_dir_Trans(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_TERGM_dir_Trans(theta, gamma, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_TERGM_dir_Trans
float ELBO_conv_TERGM_dir_Trans(mat gamma, vec alpha, vec theta, cube network, cube Trans_stat, int N, int K, int T_data);
RcppExport SEXP TERGMdirTrans_ELBO_conv_TERGM_dir_Trans(SEXP gammaSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_TERGM_dir_Trans(gamma, alpha, theta, network, Trans_stat, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// grad_TERGM_dir_K1_Trans
float grad_TERGM_dir_K1_Trans(float theta, cube network, cube Trans_stat, int N, int T_data);
RcppExport SEXP TERGMdirTrans_grad_TERGM_dir_K1_Trans(SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_TERGM_dir_K1_Trans(theta, network, Trans_stat, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// hess_TERGM_dir_K1_Trans
float hess_TERGM_dir_K1_Trans(float theta, int N, int T_data);
RcppExport SEXP TERGMdirTrans_hess_TERGM_dir_K1_Trans(SEXP thetaSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_TERGM_dir_K1_Trans(theta, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_TERGM_dir_K1_Trans
float ELBO_conv_TERGM_dir_K1_Trans(float theta, cube network, cube Trans_stat, int N, int T_data);
RcppExport SEXP TERGMdirTrans_ELBO_conv_TERGM_dir_K1_Trans(SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_TERGM_dir_K1_Trans(theta, network, Trans_stat, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
