// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;
using namespace std;

// rowsum_Mat
vec rowsum_Mat(mat M);
RcppExport SEXP HMMEMundirStab_rowsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// colsum_Mat
vec colsum_Mat(mat M);
RcppExport SEXP HMMEMundirStab_colsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(colsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// epan
float epan(float input);
RcppExport SEXP HMMEMundirStab_epan(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(epan(input));
    return rcpp_result_gen;
END_RCPP
}
// gamma_init_update_HMM_undir_Stab
mat gamma_init_update_HMM_undir_Stab(mat gamma_init, vec log_alpha, vec theta, cube network_12, int N, int K);
RcppExport SEXP HMMEMundirStab_gamma_init_update_HMM_undir_Stab(SEXP gamma_initSEXP, SEXP log_alphaSEXP, SEXP thetaSEXP, SEXP network_12SEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< vec >::type log_alpha(log_alphaSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network_12(network_12SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_init_update_HMM_undir_Stab(gamma_init, log_alpha, theta, network_12, N, K));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update_HMM_undir_Stab
cube gamma_update_HMM_undir_Stab(mat gamma_init, cube Tau, int N, int K, int T_data);
RcppExport SEXP HMMEMundirStab_gamma_update_HMM_undir_Stab(SEXP gamma_initSEXP, SEXP TauSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< cube >::type Tau(TauSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update_HMM_undir_Stab(gamma_init, Tau, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// Tau_update_HMM_undir_Stab
field<mat> Tau_update_HMM_undir_Stab(cube gamma, cube log_pi, vec theta, cube network, int N, int K, int T_data);
RcppExport SEXP HMMEMundirStab_Tau_update_HMM_undir_Stab(SEXP gammaSEXP, SEXP log_piSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< cube >::type log_pi(log_piSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Tau_update_HMM_undir_Stab(gamma, log_pi, theta, network, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_undir_Stab
mat grad_HMM_undir_Stab(vec theta, cube gamma, cube network, int N, int K, int T_data);
RcppExport SEXP HMMEMundirStab_grad_HMM_undir_Stab(SEXP thetaSEXP, SEXP gammaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_undir_Stab(theta, gamma, network, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_undir_Stab
mat hess_HMM_undir_Stab(vec theta, cube gamma, int N, int K, int T_data);
RcppExport SEXP HMMEMundirStab_hess_HMM_undir_Stab(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_undir_Stab(theta, gamma, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_undir_Stab
float ELBO_conv_HMM_undir_Stab(cube gamma, vec alpha, cube pi, cube Tau, vec theta, cube network, int N, int K, int T_data);
RcppExport SEXP HMMEMundirStab_ELBO_conv_HMM_undir_Stab(SEXP gammaSEXP, SEXP alphaSEXP, SEXP piSEXP, SEXP TauSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< cube >::type pi(piSEXP);
    Rcpp::traits::input_parameter< cube >::type Tau(TauSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_undir_Stab(gamma, alpha, pi, Tau, theta, network, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_undir_K1_Stab
float grad_HMM_undir_K1_Stab(float theta, cube network, int N, int T_data);
RcppExport SEXP HMMEMundirStab_grad_HMM_undir_K1_Stab(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_undir_K1_Stab(theta, network, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_undir_K1_Stab
float hess_HMM_undir_K1_Stab(float theta, int N, int T_data);
RcppExport SEXP HMMEMundirStab_hess_HMM_undir_K1_Stab(SEXP thetaSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_undir_K1_Stab(theta, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_undir_K1_Stab
float ELBO_conv_HMM_undir_K1_Stab(float theta, cube network, int N, int T_data);
RcppExport SEXP HMMEMundirStab_ELBO_conv_HMM_undir_K1_Stab(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_undir_K1_Stab(theta, network, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
