# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('HMMEMundirStab_rowsum_Mat', PACKAGE = 'HMMEMundirStab', M)
}

colsum_Mat <- function(M) {
    .Call('HMMEMundirStab_colsum_Mat', PACKAGE = 'HMMEMundirStab', M)
}

epan <- function(input) {
    .Call('HMMEMundirStab_epan', PACKAGE = 'HMMEMundirStab', input)
}

gamma_init_update_HMM_undir_Stab <- function(gamma_init, log_alpha, theta, network_12, N, K) {
    .Call('HMMEMundirStab_gamma_init_update_HMM_undir_Stab', PACKAGE = 'HMMEMundirStab', gamma_init, log_alpha, theta, network_12, N, K)
}

gamma_update_HMM_undir_Stab <- function(gamma_init, Tau, N, K, T_data) {
    .Call('HMMEMundirStab_gamma_update_HMM_undir_Stab', PACKAGE = 'HMMEMundirStab', gamma_init, Tau, N, K, T_data)
}

Tau_update_HMM_undir_Stab <- function(gamma, log_pi, theta, network, N, K, T_data) {
    .Call('HMMEMundirStab_Tau_update_HMM_undir_Stab', PACKAGE = 'HMMEMundirStab', gamma, log_pi, theta, network, N, K, T_data)
}

grad_HMM_undir_Stab <- function(theta, gamma, network, N, K, T_data) {
    .Call('HMMEMundirStab_grad_HMM_undir_Stab', PACKAGE = 'HMMEMundirStab', theta, gamma, network, N, K, T_data)
}

hess_HMM_undir_Stab <- function(theta, gamma, N, K, T_data) {
    .Call('HMMEMundirStab_hess_HMM_undir_Stab', PACKAGE = 'HMMEMundirStab', theta, gamma, N, K, T_data)
}

ELBO_conv_HMM_undir_Stab <- function(gamma, alpha, pi, Tau, theta, network, N, K, T_data) {
    .Call('HMMEMundirStab_ELBO_conv_HMM_undir_Stab', PACKAGE = 'HMMEMundirStab', gamma, alpha, pi, Tau, theta, network, N, K, T_data)
}

grad_HMM_undir_K1_Stab <- function(theta, network, N, T_data) {
    .Call('HMMEMundirStab_grad_HMM_undir_K1_Stab', PACKAGE = 'HMMEMundirStab', theta, network, N, T_data)
}

hess_HMM_undir_K1_Stab <- function(theta, N, T_data) {
    .Call('HMMEMundirStab_hess_HMM_undir_K1_Stab', PACKAGE = 'HMMEMundirStab', theta, N, T_data)
}

ELBO_conv_HMM_undir_K1_Stab <- function(theta, network, N, T_data) {
    .Call('HMMEMundirStab_ELBO_conv_HMM_undir_K1_Stab', PACKAGE = 'HMMEMundirStab', theta, network, N, T_data)
}

