// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace std;
using namespace arma;

// rowsum_Mat
vec rowsum_Mat(mat M);
RcppExport SEXP HMMEMdirTrans_rowsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// colsum_Mat
vec colsum_Mat(mat M);
RcppExport SEXP HMMEMdirTrans_colsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(colsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// epan
float epan(float input);
RcppExport SEXP HMMEMdirTrans_epan(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(epan(input));
    return rcpp_result_gen;
END_RCPP
}
// Trans_stat_cal
cube Trans_stat_cal(cube network, int N, int T_data);
RcppExport SEXP HMMEMdirTrans_Trans_stat_cal(SEXP networkSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Trans_stat_cal(network, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// gamma_init_update_HMM_dir_Trans
mat gamma_init_update_HMM_dir_Trans(mat gamma_init, vec log_alpha, vec theta, cube network_12, mat Trans_stat_12, int N, int K);
RcppExport SEXP HMMEMdirTrans_gamma_init_update_HMM_dir_Trans(SEXP gamma_initSEXP, SEXP log_alphaSEXP, SEXP thetaSEXP, SEXP network_12SEXP, SEXP Trans_stat_12SEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< vec >::type log_alpha(log_alphaSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network_12(network_12SEXP);
    Rcpp::traits::input_parameter< mat >::type Trans_stat_12(Trans_stat_12SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_init_update_HMM_dir_Trans(gamma_init, log_alpha, theta, network_12, Trans_stat_12, N, K));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update_HMM_dir_Trans
cube gamma_update_HMM_dir_Trans(mat gamma_init, cube Tau, int N, int K, int T_data);
RcppExport SEXP HMMEMdirTrans_gamma_update_HMM_dir_Trans(SEXP gamma_initSEXP, SEXP TauSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< cube >::type Tau(TauSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update_HMM_dir_Trans(gamma_init, Tau, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// Tau_update_HMM_dir_Trans
field<mat> Tau_update_HMM_dir_Trans(cube gamma, cube log_pi, vec theta, cube network, cube Trans_stat, int N, int K, int T_data);
RcppExport SEXP HMMEMdirTrans_Tau_update_HMM_dir_Trans(SEXP gammaSEXP, SEXP log_piSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< cube >::type log_pi(log_piSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Tau_update_HMM_dir_Trans(gamma, log_pi, theta, network, Trans_stat, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_dir_Trans
mat grad_HMM_dir_Trans(vec theta, cube gamma, cube network, cube Trans_stat, int N, int K, int T_data);
RcppExport SEXP HMMEMdirTrans_grad_HMM_dir_Trans(SEXP thetaSEXP, SEXP gammaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_dir_Trans(theta, gamma, network, Trans_stat, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_dir_Trans
mat hess_HMM_dir_Trans(vec theta, cube gamma, int N, int K, int T_data);
RcppExport SEXP HMMEMdirTrans_hess_HMM_dir_Trans(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_dir_Trans(theta, gamma, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_dir_Trans
float ELBO_conv_HMM_dir_Trans(cube gamma, vec alpha, cube pi, cube Tau, vec theta, cube network, cube Trans_stat, int N, int K, int T_data);
RcppExport SEXP HMMEMdirTrans_ELBO_conv_HMM_dir_Trans(SEXP gammaSEXP, SEXP alphaSEXP, SEXP piSEXP, SEXP TauSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP KSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< cube >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< cube >::type pi(piSEXP);
    Rcpp::traits::input_parameter< cube >::type Tau(TauSEXP);
    Rcpp::traits::input_parameter< vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_dir_Trans(gamma, alpha, pi, Tau, theta, network, Trans_stat, N, K, T_data));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_dir_K1_Trans
float grad_HMM_dir_K1_Trans(float theta, cube network, cube Trans_stat, int N, int T_data);
RcppExport SEXP HMMEMdirTrans_grad_HMM_dir_K1_Trans(SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_dir_K1_Trans(theta, network, Trans_stat, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_dir_K1_Trans
float hess_HMM_dir_K1_Trans(float theta, int N, int T_data);
RcppExport SEXP HMMEMdirTrans_hess_HMM_dir_K1_Trans(SEXP thetaSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_dir_K1_Trans(theta, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_dir_K1_Trans
float ELBO_conv_HMM_dir_K1_Trans(float theta, cube network, cube Trans_stat, int N, int T_data);
RcppExport SEXP HMMEMdirTrans_ELBO_conv_HMM_dir_K1_Trans(SEXP thetaSEXP, SEXP networkSEXP, SEXP Trans_statSEXP, SEXP NSEXP, SEXP T_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< cube >::type network(networkSEXP);
    Rcpp::traits::input_parameter< cube >::type Trans_stat(Trans_statSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type T_data(T_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_dir_K1_Trans(theta, network, Trans_stat, N, T_data));
    return rcpp_result_gen;
END_RCPP
}
