# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('TERGMundirStab_rowsum_Mat', PACKAGE = 'TERGMundirStab', M)
}

colsum_Mat <- function(M) {
    .Call('TERGMundirStab_colsum_Mat', PACKAGE = 'TERGMundirStab', M)
}

epan <- function(input) {
    .Call('TERGMundirStab_epan', PACKAGE = 'TERGMundirStab', input)
}

gamma_update_TERGM_undir_Stab <- function(gamma, pi, theta, network, N, K, T_data) {
    .Call('TERGMundirStab_gamma_update_TERGM_undir_Stab', PACKAGE = 'TERGMundirStab', gamma, pi, theta, network, N, K, T_data)
}

grad_TERGM_undir_Stab <- function(theta, gamma, network, N, K, T_data) {
    .Call('TERGMundirStab_grad_TERGM_undir_Stab', PACKAGE = 'TERGMundirStab', theta, gamma, network, N, K, T_data)
}

hess_TERGM_undir_Stab <- function(theta, gamma, N, K, T_data) {
    .Call('TERGMundirStab_hess_TERGM_undir_Stab', PACKAGE = 'TERGMundirStab', theta, gamma, N, K, T_data)
}

ELBO_conv_TERGM_undir_Stab <- function(gamma, alpha, theta, network, N, K, T_data) {
    .Call('TERGMundirStab_ELBO_conv_TERGM_undir_Stab', PACKAGE = 'TERGMundirStab', gamma, alpha, theta, network, N, K, T_data)
}

grad_TERGM_undir_K1_Stab <- function(theta, network, N, T_data) {
    .Call('TERGMundirStab_grad_TERGM_undir_K1_Stab', PACKAGE = 'TERGMundirStab', theta, network, N, T_data)
}

hess_TERGM_undir_K1_Stab <- function(theta, N, T_data) {
    .Call('TERGMundirStab_hess_TERGM_undir_K1_Stab', PACKAGE = 'TERGMundirStab', theta, N, T_data)
}

ELBO_conv_TERGM_undir_K1_Stab <- function(theta, network, N, T_data) {
    .Call('TERGMundirStab_ELBO_conv_TERGM_undir_K1_Stab', PACKAGE = 'TERGMundirStab', theta, network, N, T_data)
}

