# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('HMMEMdirTrans_rowsum_Mat', PACKAGE = 'HMMEMdirTrans', M)
}

colsum_Mat <- function(M) {
    .Call('HMMEMdirTrans_colsum_Mat', PACKAGE = 'HMMEMdirTrans', M)
}

epan <- function(input) {
    .Call('HMMEMdirTrans_epan', PACKAGE = 'HMMEMdirTrans', input)
}

Trans_stat_cal <- function(network, N, T_data) {
    .Call('HMMEMdirTrans_Trans_stat_cal', PACKAGE = 'HMMEMdirTrans', network, N, T_data)
}

gamma_init_update_HMM_dir_Trans <- function(gamma_init, log_alpha, theta, network_12, Trans_stat_12, N, K) {
    .Call('HMMEMdirTrans_gamma_init_update_HMM_dir_Trans', PACKAGE = 'HMMEMdirTrans', gamma_init, log_alpha, theta, network_12, Trans_stat_12, N, K)
}

gamma_update_HMM_dir_Trans <- function(gamma_init, Tau, N, K, T_data) {
    .Call('HMMEMdirTrans_gamma_update_HMM_dir_Trans', PACKAGE = 'HMMEMdirTrans', gamma_init, Tau, N, K, T_data)
}

Tau_update_HMM_dir_Trans <- function(gamma, log_pi, theta, network, Trans_stat, N, K, T_data) {
    .Call('HMMEMdirTrans_Tau_update_HMM_dir_Trans', PACKAGE = 'HMMEMdirTrans', gamma, log_pi, theta, network, Trans_stat, N, K, T_data)
}

grad_HMM_dir_Trans <- function(theta, gamma, network, Trans_stat, N, K, T_data) {
    .Call('HMMEMdirTrans_grad_HMM_dir_Trans', PACKAGE = 'HMMEMdirTrans', theta, gamma, network, Trans_stat, N, K, T_data)
}

hess_HMM_dir_Trans <- function(theta, gamma, N, K, T_data) {
    .Call('HMMEMdirTrans_hess_HMM_dir_Trans', PACKAGE = 'HMMEMdirTrans', theta, gamma, N, K, T_data)
}

ELBO_conv_HMM_dir_Trans <- function(gamma, alpha, pi, Tau, theta, network, Trans_stat, N, K, T_data) {
    .Call('HMMEMdirTrans_ELBO_conv_HMM_dir_Trans', PACKAGE = 'HMMEMdirTrans', gamma, alpha, pi, Tau, theta, network, Trans_stat, N, K, T_data)
}

grad_HMM_dir_K1_Trans <- function(theta, network, Trans_stat, N, T_data) {
    .Call('HMMEMdirTrans_grad_HMM_dir_K1_Trans', PACKAGE = 'HMMEMdirTrans', theta, network, Trans_stat, N, T_data)
}

hess_HMM_dir_K1_Trans <- function(theta, N, T_data) {
    .Call('HMMEMdirTrans_hess_HMM_dir_K1_Trans', PACKAGE = 'HMMEMdirTrans', theta, N, T_data)
}

ELBO_conv_HMM_dir_K1_Trans <- function(theta, network, Trans_stat, N, T_data) {
    .Call('HMMEMdirTrans_ELBO_conv_HMM_dir_K1_Trans', PACKAGE = 'HMMEMdirTrans', theta, network, Trans_stat, N, T_data)
}

