# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('HMMEMundir_rowsum_Mat', PACKAGE = 'HMMEMundir', M)
}

colsum_Mat <- function(M) {
    .Call('HMMEMundir_colsum_Mat', PACKAGE = 'HMMEMundir', M)
}

epan <- function(input) {
    .Call('HMMEMundir_epan', PACKAGE = 'HMMEMundir', input)
}

gamma_init_update_HMM_undir <- function(gamma_init, log_alpha, theta, network_init, N, K) {
    .Call('HMMEMundir_gamma_init_update_HMM_undir', PACKAGE = 'HMMEMundir', gamma_init, log_alpha, theta, network_init, N, K)
}

gamma_update_HMM_undir <- function(gamma_init, Tau, N, K, T_data) {
    .Call('HMMEMundir_gamma_update_HMM_undir', PACKAGE = 'HMMEMundir', gamma_init, Tau, N, K, T_data)
}

Tau_update_HMM_undir <- function(gamma, log_pi, theta, network, N, K, T_data) {
    .Call('HMMEMundir_Tau_update_HMM_undir', PACKAGE = 'HMMEMundir', gamma, log_pi, theta, network, N, K, T_data)
}

grad_HMM_undir <- function(theta, gamma, network, N, K, T_data) {
    .Call('HMMEMundir_grad_HMM_undir', PACKAGE = 'HMMEMundir', theta, gamma, network, N, K, T_data)
}

hess_HMM_undir <- function(theta, gamma, N, K, T_data) {
    .Call('HMMEMundir_hess_HMM_undir', PACKAGE = 'HMMEMundir', theta, gamma, N, K, T_data)
}

ELBO_conv_HMM_undir <- function(gamma, alpha, pi, Tau, theta, network, N, K, T_data) {
    .Call('HMMEMundir_ELBO_conv_HMM_undir', PACKAGE = 'HMMEMundir', gamma, alpha, pi, Tau, theta, network, N, K, T_data)
}

grad_HMM_undir_K1 <- function(theta, network, N, T_data) {
    .Call('HMMEMundir_grad_HMM_undir_K1', PACKAGE = 'HMMEMundir', theta, network, N, T_data)
}

hess_HMM_undir_K1 <- function(theta, N, T_data) {
    .Call('HMMEMundir_hess_HMM_undir_K1', PACKAGE = 'HMMEMundir', theta, N, T_data)
}

ELBO_conv_HMM_undir_K1 <- function(theta, network, N, T_data) {
    .Call('HMMEMundir_ELBO_conv_HMM_undir_K1', PACKAGE = 'HMMEMundir', theta, network, N, T_data)
}

